Document: journalbeat
Title: Debian journalbeat Manual
Author: <insert document author here>
Abstract: This manual describes what journalbeat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/journalbeat/journalbeat.sgml.gz

Format: postscript
Files: /usr/share/doc/journalbeat/journalbeat.ps.gz

Format: text
Files: /usr/share/doc/journalbeat/journalbeat.text.gz

Format: HTML
Index: /usr/share/doc/journalbeat/html/index.html
Files: /usr/share/doc/journalbeat/html/*.html
